---
title: "Merge Data"
author: "London Wagner"
date: "1/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(betareg)
```


```{r}
states <- read_csv("GOVT020/winter-inst-2021/data/state_raw.csv")
yale <- read_csv("GOVT020/winter-inst-2021/data/yale_data_raw.csv")
head(states)
head(yale)
```

```{r}
yale <- yale%>%
  filter(GeoType == "State")%>%
  select(GeoName, human, humanOppose, happening, happeningOppose, gwvoteimp, gwvoteimpOppose)
```

```{r}
ggplot(data = state_yale)+
  geom_point(aes(x = cp_2019, y = gwvoteimp)) +
  theme_bw()
```


```{r}
state_yale <-inner_join(yale, states, by = c("GeoName" = "state"))
state_yale%>%
  arrange(GeoName)%>%
  mutate(gov_party = as.factor(gov_party))-> state_yale

state_yale$cp <- ifelse(state_yale$cp_2019 > 0, 1, 0)
state_yale$cp <- as.factor(state_yale$cp)
```

```{r}
ggplot(data = state_yale) +
  geom_boxplot(aes(x = cp, y = gwvoteimp, fill = cp))
```


```{r}
climate_reg <- lm(gwvoteimp ~ cp + gov_party + co2_emissions + perc_renew + perc_ff, data = state_yale)

summary(climate_reg)

climate_reg2 <- lm(gwvoteimp ~ cp + gov_party + co2_emissions + perc_renew + perc_ff + pop + perc_white + perc_black + perc_latino + perc_asian, data = state_yale)

summary(climate_reg2)
```

```{r}
state_yale$gwvoteimp <- state_yale$gwvoteimp/100

climate_reg3 <- betareg(gwvoteimp ~ cp + gov_party + co2_emissions + perc_renew + perc_ff, data = state_yale)

summary(climate_reg3)

climate_reg4 <- betareg(gwvoteimp ~ cp + gov_party + co2_emissions + perc_renew + perc_ff + pop + perc_white + perc_black + perc_latino + perc_asian, data = state_yale)

summary(climate_reg4)
```

